Updated the platform structure and included UEFI hardwarefeature
mjeyarax/platform-info pull request #1
Opened 2020-12-15 11:29 UTC by mjeyarax

Platform info library changes with respect to event log collection enhancement. 
Please note that PFR and BMC hardwarefeature included in PlatformInfo json strucuture but the implementation is not done as the discussion is still in progress.

2020-12-18 22:57 UTC, kwtj43 requested changes

2020-12-18 22:57 UTC, kwtj43 commented on platforminfo/platform_info_linux.go
> +	_, err := os.Stat("/sys/firmware/efi")
I think this should use os.IsNotExist for file presence...

if _, err := os.Stat("/sys/firmware/efi"); os.IsNotExist(err) {
  // path/to/whatever does not exist
}

2020-12-21 10:58 UTC, ddhawal commented on platforminfo/platform_info.go
> +//				"enabled": "true",
fix indentation

2020-12-21 15:15 UTC, kwtj43 approved these changes

2020-12-30 09:08 UTC, merged